"""Constantes du jeu Neuron Boxing.

Source de vérité : docs/RULES.md. Toute modification d'une valeur de design
incrémente RULESET_VERSION.
"""

import math

# --- Contrats de version ---
RULESET_VERSION = 1
OBS_VERSION = 1
ACTION_VERSION = 1

OBS_SIZE = 20
N_ACTIONS = 10

# --- Temps ---
TICKS_PER_SECOND = 30
MAX_TICKS = 450  # 15 secondes

# --- Ring ---

RING_SIZE = 8.0
RING_DIAGONAL = RING_SIZE * math.sqrt(2)

# --- Boxeur ---

MAX_HP = 100.0
BODY_RADIUS = 0.4
MIN_SEPARATION = 2 * BODY_RADIUS
MOVE_SPEED = 0.12
START_DISTANCE = 3.0

# --- Coup ---

PUNCH_RANGE = 1.4
PUNCH_DAMAGE = 15.0
PUNCH_WINDUP = 5
PUNCH_ACTIVE = 2
PUNCH_RECOVERY = 8
PUNCH_COOLDOWN = 5
PUNCH_CYCLE = PUNCH_WINDUP + PUNCH_ACTIVE + PUNCH_RECOVERY + PUNCH_COOLDOWN
WINDUP_END = PUNCH_CYCLE - PUNCH_WINDUP
ACTIVE_END = WINDUP_END - PUNCH_ACTIVE
RECOVERY_END = ACTIVE_END - PUNCH_RECOVERY

# --- Resultat ---

RESULT_ONGOING = None
RESULT_DRAW = -1
RESULT_P0_WINS = 0
RESULT_P1_WINS = 1

assert PUNCH_CYCLE == PUNCH_WINDUP + PUNCH_ACTIVE + PUNCH_RECOVERY + PUNCH_COOLDOWN
assert RECOVERY_END == PUNCH_COOLDOWN
